FROM python:2.7

RUN apt-get update
RUN apt-get install -y gcc g++ make libjpeg-dev libz-dev\
    libfreetype6-dev liblcms2-dev libxml2-dev libxslt-dev ocaml-nox git-core python-imaging\
    python-lxml texlive-latex-recommended ploticus dvipng imagemagick pdftk
